# Event API - Development Environment
# This compose file is for local development with external database
# Production uses `flox containerize` to create unified containers for Coolify

services:
  # Database service for development
  # In production, this may be externally managed
  database:
    image: pgvector/pgvector:pg15
    container_name: event-api-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-event_api_dev}
      POSTGRES_USER: ${POSTGRES_USER:-event_api}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-development_password}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/docker/init-db.sql:/docker-entrypoint-initdb.d/01-init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-event_api} -d ${POSTGRES_DB:-event_api_dev}"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - event-api-network

  # Development proxy for testing service integration
  # In production, services run within the Flox container
  dev-proxy:
    image: nginx:alpine
    container_name: event-api-proxy
    ports:
      - "3000:3000"  # Hono API
      - "4000:4000"  # Elixir Service
      - "8080:8080"  # BAML Service
    volumes:
      - ./scripts/docker/dev-nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - database
    networks:
      - event-api-network
    profiles:
      - dev-proxy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional containerized services for development
  # Use profile 'dev-containers' to run services in containers instead of host
  hono-dev:
    build:
      context: .
      dockerfile: services/hono-api/Dockerfile.dev
    container_name: event-api-hono-dev
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://${POSTGRES_USER:-event_api}:${POSTGRES_PASSWORD:-development_password}@database:5432/${POSTGRES_DB:-event_api_dev}
      - ELIXIR_SERVICE_URL=http://elixir-dev:4000
      - BAML_SERVICE_URL=http://baml-dev:8080
    depends_on:
      database:
        condition: service_healthy
    networks:
      - event-api-network
    profiles:
      - dev-containers
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  elixir-dev:
    build:
      context: .
      dockerfile: services/elixir_service/Dockerfile.dev
    container_name: event-api-elixir-dev
    ports:
      - "4001:4000"
    environment:
      - MIX_ENV=dev
      - DATABASE_URL=postgresql://${POSTGRES_USER:-event_api}:${POSTGRES_PASSWORD:-development_password}@database:5432/${POSTGRES_DB:-event_api_dev}
      - HONO_API_URL=http://hono-dev:3000
      - BAML_SERVICE_URL=http://baml-dev:8080
    depends_on:
      database:
        condition: service_healthy
    networks:
      - event-api-network
    profiles:
      - dev-containers
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  baml-dev:
    build:
      context: .
      dockerfile: services/baml-service/Dockerfile.dev
    container_name: event-api-baml-dev
    ports:
      - "8081:8080"
    environment:
      - NODE_ENV=development
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - event-api-network
    profiles:
      - dev-containers
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local

networks:
  event-api-network:
    driver: bridge
    name: event-api-network

# Environment variables can be set in .env file:
# POSTGRES_DB=event_api_dev
# POSTGRES_USER=event_api  
# POSTGRES_PASSWORD=development_password
# DB_PORT=5432